parameters:
    acme.admin.filter.number_range: Acme\DemoBundle\Filter\NumberRangeFilter
    acme.admin.form.number_range: Acme\DemoBundle\Form\NumberRangeType

services:
    acme.admin.filter.type.number_range:
        class: %acme.admin.filter.number_range%
        tags:
            - { name: sonata.admin.filter.type, alias: doctrine_orm_number_range }

    acme.admin.form.type.number_range:
        class: %acme.admin.form.number_range%
        arguments: [ '@service_container'  ]
        tags:
            - { name: form.type, alias: acme_admin_type_number_range }
